### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by hmaesta** [bztes/svelte-rip#1]
![Screen Shot 2021-08-20 at 09 46 46](https://user-images.githubusercontent.com/741969/130235305-766143d7-1388-4605-a59c-cc039f08e13d.png)

Is `svelte-rip` in npm? 😅

**Comment by bztes** [comment]
Obviously not. :) But I can publish a release within the next days if you are interested. Probably need to do some cleanup first.

**Comment by bztes** [comment]
https://www.npmjs.com/package/@bztes/svelte-rip
